version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Устранение проблем с горячей перезагрузкой на Windows

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
